### ISSUE TITLE
Placeholder replacement fails if values bound before execute, and could be configurable

### ISSUE THREAD

**Issue by bigpresh** [zorgnax/dbilog#11]
I noticed while using it that the attempt to replace placeholders in queries with their quoted values doesn't work if the values for those placeholders were supplied by binding the params before calling execute, e.g. `$sth->bind_param(1, 'foo');`

I've seen this happening with code using DBIx::Class.

Maybe the values could be introspected from the statement handle... or maybe just documenting that they won't be replaced in the logged query if bound in that manner would suffice.

Also - with some drivers - `DBD::Pg` for sure, and others) you can use more complex placeholders, which the current approach wouldn't work with anyway - dollar placeholders e.g. `$dbh->prepare('SELECT count(*) FROM pg_class WHERE relpages BETWEEN $1 AND $2';`);` or even named placeholders - something like:

```perl
my $sth = $dbh->prepare('SELECT COUNT(*) FROM table WHERE foo = :foo and bar = :bar');
$sth->bind_param('foo', 'value for foo');
$sth->bind_param('bar', 'value for bar');
$sth->execute;
```

*However* - in some cases it's useful to not see the args the query was run as, e.g. looking to see which particular queries execute far too many times or are slow, it's useful to aggregate by the query, not caring much for what particular params were passed to it (e.g. I might want to see just a load of `SELECT * FROM big_slow_table WHERE id = ?`, not individual ones for every ID I queried for) - so it would be useful for the placeholder replacement to be configurable anyway.

**Comment by zorgnax** [comment]
I tried my best to follow the DBI code to find out how bind_param() works, and it's literally impossible to do. DBI is just way too complicated.

The bind_param() function is defined in the DBD::SQLite module (and something similar would be in whatever DBD:: module is being used), in SQLite.xs which includes the SQLite.xsi file, in there it defines the bind_param() function which calls out to sqlite_bind_ph() function in dbdimp.c which gets a imp_sth variable which is an "implementation" $sth. Any parameters you send will end up in imp_sth->params, and fetched back out when $sth->execute() gets called.

I know that DBI hides the state of it's variables in hidden variables, and they are kinda tricky to get at. So if you looked at the contents of $sth, it seems like nothings there, but if you get a reference to the inner $sth, you can see more fields it has on the statement. You can access it like this:

```
my (undef, $inner_sth) = DBI::_handles($sth);
print Dumper($inner_sth);
```

but that $inner_sth doesn't have any references to the params that came from bind_param().

I could overwrite the bind_param() function and remember the params for later, then use them when I want to print the sql out to the log, but I'd rather not get too carried away with it, and keep the module simple and working for the 90% cases, and if they use bind_param() the log will just have ?'s in it still.

**Comment by zorgnax** [comment]
You can get access to the params from bind_param() using $sth->{ParamValues}. Maybe I can use this...

**Comment by zorgnax** [comment]
Yep, I got it, and it's in the module now. It uses $sth->{ParamValues} to get at the params added with $sth->bind_param().

**Comment by bigpresh** [comment]
Nice one!
