### ISSUE TITLE
How to log when using it as a CGI script

### ISSUE THREAD

**Issue by djuarezg** [zorgnax/dbilog#6]
@zorgnax How can you log to a file or to httpd logs when using this module?

I have a client that contacts a server and when using this module all I get is an Internal server error.

On the server side I get the following on the involved file specification:

```
BEGIN failed--compilation aborted at /usr/share/perl5/mything/image.pm line 37, <DATA> line 755
```

If I remove the file specification I don't see the log anywhere.

**Comment by zorgnax** [comment]
If there's a problem, there should be a message in /var/log/apache2/error.log. This file might be somewhere else depending on how apache is installed. This is also where it logs dbi calls to by default if you don't give it an explicit file name.
