### ISSUE TITLE
Ability to skip certain packages when looking for originator

### ISSUE THREAD

**Issue by bigpresh** [zorgnax/dbilog#7]
It would be really useful to have an option for packages to ignore when looking for the caller, vaguely like `%Carp::CarpInternal`.

For e.g. in an app that uses DBIx::Class, the log output shows me:

```
-- Tue Jan 10 20:43:57 2023
-- execute /usr/local/lib/perl5/DBIx/Class/Storage/DBI.pm 1958
SELECT ....

-- Tue Jan 10 20:43:59 2023
-- execute /usr/local/lib/perl5/DBIx/Class/Storage/DBI.pm 1958
SELECT ...
```

It's of very little interest to me that the DBI query originated from DBIx::Class - I want to know where _that_ was called from - i.e. the bit of my code which initiated the query.

I'd like to be able to set an option to omit all of DBIx::Class, for instance, so the code could look at the call stack and keep looking downwards until it finds something that doesn't match the "omit" pattern(s).

(Yeah, I could set DBIx::Class's `debug()` and maybe `debugobj()`, but in some places we go direct to DBI for elaborate hand-rolled reporting queries, etc - so logging at the DBI level is ideal to capture both; and this would also apply to other uses of DBI with *something* in front, whether that's someone's hand-rolled ORM solution or whatever.)

**Comment by zorgnax** [comment]
Problem with that is not all the DBIx::Class additions to the stack are in the DBIx::Class name space, so if you're using DBIx::Class a stack trace would look like this:

```
DBI::Log                           DBI::Log::pre_query
DBIx::Class::Storage::DBI          DBI::Log::__ANON__
DBIx::Class::Storage::DBI::SQLite  DBIx::Class::Storage::DBI::_dbh_execute
DBIx::Class::Storage::DBI          DBIx::Class::Storage::DBI::SQLite::_dbh_execute
DBIx::Class::Storage::BlockRunner  DBIx::Class::Storage::DBI::__ANON__
Try::Tiny                          DBIx::Class::Storage::BlockRunner::try {...} 
Try::Tiny                          (eval)
DBIx::Class::Storage::BlockRunner  Try::Tiny::try
Context::Preserve                  DBIx::Class::Storage::BlockRunner::__ANON__
DBIx::Class::Storage::BlockRunner  Context::Preserve::preserve_context
DBIx::Class::Storage::BlockRunner  DBIx::Class::Storage::BlockRunner::_run
DBIx::Class::Storage::DBI          DBIx::Class::Storage::BlockRunner::run
DBIx::Class::Storage::DBI          DBIx::Class::Storage::DBI::dbh_do
DBIx::Class::Storage::DBI          DBIx::Class::Storage::DBI::_execute
DBIx::Class::Storage::DBI::Cursor  DBIx::Class::Storage::DBI::_select
DBIx::Class::ResultSet             DBIx::Class::Storage::DBI::Cursor::next
DBIx::Class::ResultSet             DBIx::Class::ResultSet::_construct_results
DBIx::Class::ResultSet             DBIx::Class::ResultSet::next
main                               DBIx::Class::ResultSet::first
main                               main::get_artist_by_cd
```

If I filtered out any function calls from within a package that matches DBIx::Class it would still have Context::Preserve and Try::Tiny in there, and you wouldn't want that. So the way to do it would be to order the call stack highest to lowest, so from the main script down to the DBI call, then as soon as it transitions into the class to exclude, break from showing more stack trace entries. By default, it will do this with the DBI::Log package. 

I also noticed I like stack traces to be ordered from high level to low level, so I reversed the order I used to have it.

I added the option called exclude to the module and you can use it like this:

```
use DBI::Log exclude => ["DBIx::Class"];
```

and it will show a stack trace like this:

```
-- Tue Jan 10 17:39:17 2023
-- get_artist_by_track ./testdb.pl 24
-- first ./testdb.pl 110
SELECT me.artistid, me.name FROM artist me LEFT JOIN cd cds ON cds.artistid = me.artistid LEFT JOIN track tracks ON tracks.cdid = cds.cdid WHERE ( tracks.title = NULL )
```

if you don't have trace => 1 set, it would look like this:

```
-- Tue Jan 10 17:39:17 2023
-- first ./testdb.pl 110
SELECT me.artistid, me.name FROM artist me LEFT JOIN cd cds ON cds.artistid = me.artistid LEFT JOIN track tracks ON tracks.cdid = cds.cdid WHERE ( tracks.title = NULL )
```
