### ISSUE TITLE
Notice if given a statement handle instead of SQL and extract the query from it

### ISSUE THREAD

**Issue by bigpresh** [zorgnax/dbilog#9]
It's possible to pass a pre-prepared query to DBI's `selectrow_*`, `selectall_*`, `selectcol_arrayref` methods - i.e. any of these.

* `selectrow_array`
* `selectrow_arrayref`
* `selectrow_hashref`
* `selectall_arrayref`
* `selectall_hashref`
* `selectcol_arrayref`

The [DBI docs for selectall_arrayref](https://metacpan.org/pod/DBI#selectall_arrayref) for instance explain:

> This utility method combines "prepare", "execute" and "fetchall_arrayref" into a single call. It returns a reference to an array containing a reference to an array (or hash, see below) for each row of data fetched.
>
> The $statement parameter can be a previously prepared statement handle, in which case the prepare is skipped. This is recommended if the statement is going to be executed many times.

If the user does that - e.g.:

```perl
my $sth = $dbh->prepare($sql);
my $rows = $dbh->selectall_hashref($sth);
```
... then DBI::Log logs the statement handle as e.g. `DBI::st=HASH(0x176412d0)`.

**Comment by zorgnax** [comment]
Nice catch, this looks good.
